const root = document.querySelector('#sandbox-flow');
const status = document.querySelector('#sandbox-status');
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const readableStatus = value => ({ ACTIVE: 'Ready', REQUIRES_ACTION: 'Waiting for you', PROCESSING: 'Processing', COMPLETED: 'Complete', FAILED: 'Could not complete', EXPIRED: 'Expired', REVOKED: 'No longer available' }[value] || 'Checking');
const money = c => `S$${(c / 100).toFixed(2)}`;
const date = d => new Date(d).toLocaleString('en-SG', { timeZone: 'Asia/Singapore', dateStyle: 'medium', timeStyle: 'short' }) + ' SGT';
const button = (action, label, attrs = '') => `<button type="button" class="button" data-action="${action}" ${attrs}>${label}</button>`;
const bag = (name, small = false) => `<div class="food-pack ${small ? 'compact' : ''}" aria-hidden="true"><svg viewBox="0 0 120 150" fill="none"><path d="M27 12h66l8 126H19L27 12Z" fill="currentColor"/><path d="M29 25h62M22 124h76" stroke="#fff8ee" stroke-width="3"/><path d="M41 63 38 47l18 11h9l17-11-3 16c9 8 7 27-18 30-26-3-29-22-20-30Z" stroke="#fff8ee" stroke-width="3"/><circle cx="52" cy="72" r="2" fill="#fff8ee"/><circle cx="69" cy="72" r="2" fill="#fff8ee"/><path d="m57 82 4 3 4-3" stroke="#fff8ee" stroke-width="3"/></svg><span>${esc(name.split(' ').slice(0,2).join(' '))}</span><small>CAT FOOD</small></div>`;
let view = null, snapshot = null, detail = null, busy = false, browsing = false;
async function post(action, input = {}, route = '/api/reap') {
  const r = await fetch(route, { method: 'POST', headers: { 'content-type': 'application/json' }, credentials: 'same-origin', body: JSON.stringify(route === '/api/login' ? input : { action, input }) });
  const b = await r.json(); if (!r.ok) throw new Error(b.error || 'REQUEST_FAILED'); return b;
}
function receipt(r) {
  return `<section class="panel receipt-shop"><p class="eyebrow">CONFIRMED BY REAP</p><h2>${r.needsReconciliation ? 'Your test order needs a price check.' : 'Your test order is complete.'}</h2><p class="success-note">${r.needsReconciliation ? 'Reap returned a different total. Please ask the demo team to check it before starting another order.' : r.simulatedCheckout ? 'Reap confirmed a simulated test order. No real payment was made, and payment approval was not tested.' : 'Reap confirmed this test order. We requested a simulation, and Reap also asked for approval on its secure page.'}</p><p class="order-total">${money(r.finalCents)}</p><dl><dt>Order reference</dt><dd><code>${esc(r.orderId)}</code></dd><dt>Payment reference</dt><dd><code>${esc(r.checkoutId)}</code></dd><dt>Completed</dt><dd>${esc(date(r.completedAt))}</dd><dt>Care log</dt><dd>${r.careLogEntries} saved entry</dd></dl><p>This is a demo. No money was spent and no food will be delivered. You can come back to this receipt in the same browser.</p>${view ? `<div class="actions">${button('startNew','Shop pet food again')}${button('checkout','Show receipt again')}${button('status','Check order status')}</div>` : ''}</section>`;
}
function render() {
  if(!view) { root.innerHTML = `<section class="panel"><h2>Opening your pet-food shop…</h2><p>We’re getting your own demo cart ready.</p>${snapshot?.receipt ? receipt(snapshot.receipt) : ''}</section>`; return; }
  const s=view.selection,q=view.quote,e=view.enrollment,c=view.checkout;
  const quoteExpired=q&&Date.now()>=Date.parse(q.expiresAt);
  const step=view.receipt?4:c||(view.cartReviewed&&!quoteExpired)?3:s?2:1;
  let html=`<nav class="shop-progress" aria-label="Shopping progress">${['Choose food','Your cart','Test payment','Receipt'].map((label,i)=>`<span class="${step===i+1?'current':step>i+1?'done':''}" ${step===i+1?'aria-current="step"':''}><b>${i+1}</b>${label}</span>`).join('')}</nav>`;
  if(view.receipt) {
    html+=receipt(view.receipt);
    if(view.previousReceipts?.length) html+=`<details class="panel previous-orders"><summary>Previous test orders (${view.previousReceipts.length})</summary>${view.previousReceipts.map(r=>`<p>${esc(r.orderId)} · ${money(r.finalCents)}</p>`).join('')}</details>`;
    root.innerHTML=html;return;
  }
  const expired=Date.now()>=Date.parse(view.permissionExpiresAt);
  if(expired&&!c) html+=`<section class="panel"><h2>Ready to keep shopping?</h2><p>You’ve been away for a while. Continue below, then check your cart again.</p>${button('renewPermission','Continue shopping')}</section>`;
  if(!c&&(!s||browsing)) {
    html+=`<section class="panel shop-catalog"><div class="shop-section-heading"><div><p class="eyebrow">THE PET-FOOD SHOP</p><h2>A little backup for Milo.</h2><p>Choose one food and size. You can spend up to ${money(view.budgetCents)}, including delivery.</p></div><span class="cart-pill">Your cart · ${s?'1 item':'empty'}</span></div><div class="actions">${button('search',view.products.length?'Refresh products':'Browse pet food',expired?'disabled':'')}${s?button('showCart','Back to your cart'):''}</div><div class="product-grid">${view.products.map((p,i)=>`<article class="shop-product tone-${i%3}"><div class="product-picture">${bag(p.name)}<span class="stock-chip">${p.available?'Available in demo':'Stock unconfirmed'}</span></div><div class="product-body"><p class="merchant-name">${esc(p.merchant)}</p><h3>${esc(p.name)}</h3><p class="product-price">From ${money(p.minCents)}</p>${button('details','Choose size',`data-product="${esc(p.id)}" ${expired||!p.available?'disabled':''}`)}</div></article>`).join('')}</div><p class="small">Pack pictures are illustrations. Product names, sizes and prices come from Reap’s test catalogue.</p></section>`;
  }
  if(detail&&!c) html+=`<section class="panel product-detail"><div class="detail-picture">${bag(detail.name)}</div><div><p class="eyebrow">${esc(detail.merchant)}</p><h2>${esc(detail.name)}</h2><p>Starting size: ${esc(detail.defaultVariant.name)} · ${money(detail.defaultVariant.priceCents)}</p>${detail.options.map((o,i)=>`<label for="option-${i}">${esc(o.name)}</label><select id="option-${i}" data-option>${o.values.map(v=>`<option value="${esc(v.optionId)}" ${v.available?'':'disabled'}>${esc(v.label)}</option>`).join('')}</select>`).join('')}<p class="small">Choose a size for your one-item cart. We’ll show the full price, including delivery, before you check out.</p><p class="small">This demo does not check whether a different food is suitable for your pet’s diet.</p><label class="check-label"><input type="checkbox" id="product-consent">I choose this food and size for Milo. This choice does not approve a payment.</label><div class="actions">${button('choose','Add to cart')}${button('decline','Skip this food')}</div></div></section>`;
  if(s&&!c&&!browsing) html+=`<section class="panel shopping-cart"><div class="shop-section-heading"><div><p class="eyebrow">YOUR CART · ONE ITEM</p><h2>Check your cart.</h2></div>${button('browse','Change food','aria-label="Change selected food"')}</div><div class="cart-item">${bag(s.name,true)}<div><p class="merchant-name">${esc(s.merchant)}</p><h3>${esc(s.name)}</h3><p>${esc(s.variant.name)} · Quantity 1</p><p class="small">${s.substitute ? 'You chose this food as an alternative for Milo.' : 'You chose this food and size for Milo.'}</p></div><strong>${money(s.variant.priceCents)}</strong></div><div class="cart-summary"><div><span>Food</span><strong>${money(s.variant.priceCents)}</strong></div><div><span>Delivery</span><strong>${q?money(q.shipping.find(sh=>sh.selected)?.priceCents||0):'Calculated next'}</strong></div><div class="cart-total"><span>${q?'Total':'Item subtotal'}</span><strong>${money(q?q.finalCents:s.variant.priceCents)}</strong></div><p class="small">Your limit is ${money(view.budgetCents)}. The total includes delivery, tax and any other charges.</p></div><div class="actions">${button('quote',q?'Update delivery price':'Calculate delivery')}</div>${q?`${quoteExpired?'<p class="pending">This price has expired. Update the delivery price, then check the new total.</p>':''}${q.finalCents>view.budgetCents?'<p class="pending">This cart is over your S$65 limit. Choose a smaller size or a different food.</p>':''}<h3>Delivery</h3>${q.shipping.map(sh=>`<div class="shipping-choice"><div><strong>${esc(sh.name)} · ${money(sh.priceCents)}</strong><p>${sh.details.map(d=>`${esc(d.key)}: ${esc(d.value)}`).join('<br>')||'A delivery date is not available.'}</p></div>${button('shipping',sh.selected?'Check this delivery option':'Use this delivery option',`data-shipping="${esc(sh.id)}"`)}</div>`).join('')}<p class="small">Price valid until ${esc(date(q.expiresAt))}. Demo delivery address: Asha Demo, 1 Fictional Road, Singapore 018989. This is test information.</p><label class="check-label"><input type="checkbox" id="delivery-consent">I’ve checked the ${money(q.finalCents)} total and delivery option. I understand that delivery may not arrive in time for Milo. I’ll approve the test payment separately.</label><div class="actions">${button('approveCart','Continue to test payment',q.finalCents>view.budgetCents||quoteExpired?'disabled':'')}</div>${view.cartReviewed&&!quoteExpired?'<p class="success-note">Your cart is checked. Next, set up your test card and approve the test order.</p>':''}`:''}</section>`;
  if((view.cartReviewed||e||c)&&!browsing) html+=`<section class="panel approval-panel"><p class="eyebrow">TEST PAYMENT</p><h2>${e?.status==='ACTIVE'?'Your test card is ready.':'Set up your test card.'}</h2><p>Use the team’s sandbox test card only. Card details and verification stay on Reap’s secure page; Kampawng does not collect them.</p>${e?.status !== 'ACTIVE' ? `<p class="pending">This step sets up your card; it does not place your food order. A $0.00 amount on the setup page is not your cart total.${q ? ` Your food total is ${money(q.finalCents)}. You’ll review it separately when you place the test order.` : ''} Finish setup, return here, then click “Check card setup”.</p>` : ''}${!e?button('enrollment','Set up test card'): `<p class="status-line">Card setup: <strong>${esc(readableStatus(e.status))}</strong></p><div class="actions">${e.nextAction?`<a class="button" href="${esc(e.nextAction.url)}" target="_blank" rel="noopener noreferrer">Open secure card setup</a>`:''}${button('enrollmentStatus','Check card setup')}${['REQUIRES_ACTION','FAILED','EXPIRED'].includes(e.status)?button('renewEnrollment','Get a new setup link'):''}</div>`}${q&&e?`<div class="checkout-area"><h3>${c?'Your test order':'Ready to check out?'}</h3><p>${c?'Closing this page does not cancel your test order. Check its status here before trying anything else.':'We’ll check that your price is still valid and your total is within S$65. This is a test order; Reap may ask you to approve it on its secure page.'}</p>${c?`<p class="status-line">Order status: <strong>${esc(readableStatus(c.status))}</strong></p>${c.status==='REQUIRES_ACTION'&&c.nextAction?`<a class="button" href="${esc(c.nextAction.url)}" target="_blank" rel="noopener noreferrer">Approve on secure page</a>`:''}`:''}<div class="actions">${button(c?'status':'checkout',c?'Check order status':`Place test order · ${money(q.finalCents)}`,!c&&(!view.cartReviewed||quoteExpired||expired||e.status!=='ACTIVE')?'disabled':'')}</div></div>`:''}</section>`;
  if(view.previousReceipts?.length) html+=`<details class="panel previous-orders"><summary>Previous test orders (${view.previousReceipts.length})</summary>${view.previousReceipts.map(r=>`<p>${esc(r.orderId)} · ${money(r.finalCents)}</p>`).join('')}</details>`;
  root.innerHTML=html;
}
async function refresh(){const r=await fetch('/api/status',{credentials:'same-origin',cache:'no-store'});if(!r.ok){const d=await r.json();throw new Error(d.error||'DEMO_UNAVAILABLE');}snapshot=await r.json();view=snapshot.authenticated?await post('view'):null;render();}
const errors={DEMO_SESSION_REQUIRED:'Please reload the page to open your demo cart.',DEMO_CAPACITY_REACHED:'The demo is full right now. Your existing cart is saved. Please try again later.',DEMO_RUN_LIMIT:'You’ve reached this browser’s demo limit. Your receipts are still saved.',FINISH_CURRENT_REQUEST:'Please finish the current test order before starting another cart.',ENROLLMENT_NOT_ACTIVE:'Finish setting up your test card on the secure page, then click “Check card setup”.',OVER_BUDGET:'Your cart is over S$65. Choose a smaller size or a different food.',QUOTE_EXPIRED:'This price has expired. Update the delivery price and check the new total.',CART_CHANGED_REVIEW:'The price or delivery option changed. Please check your cart again.',CART_REAPPROVAL_REQUIRED:'Please check the updated total and tick the cart review box again.',PERMISSION_EXPIRED:'Click “Continue shopping”, then check your cart again.',RESULT_UNCERTAIN:'We couldn’t confirm what happened. Your cart is saved. The demo team needs to check it before you try again.',RATE_LIMITED:'The demo is busy. Please wait a minute and try again.',DEMO_QUERY_ONLY:'This demo only searches for cat food.',ENROLLMENT_SESSION_LIMIT:'You’ve used all the setup links for this cart. Please ask the demo team for help.',SUBSTITUTION_DECLINED:'You skipped this food earlier. Please choose another food.',PROVIDER_UNREACHABLE:'We couldn’t reach Reap. Please ask the demo team to check your cart before trying again.'};
function responseMessage(result) {
  if(result?.checkoutId) return 'Your test order is complete. Your receipt is saved below.';
  if(result?.quoteId && ['FAILED','EXPIRED'].includes(result.status)) return 'This test order could not finish. Your cart is saved. Please ask the demo team to check it before starting another order.';
  if(result?.status) return `Current status: ${readableStatus(result.status)}. Follow the next step below.`;
  if(result?.approved) return 'Your cart is checked. Continue to test payment below.';
  if(result?.denied) return 'That food was skipped. Choose another one below.';
  if(result?.variant) return 'Added to your cart. Check the item and delivery price below.';
  if(result?.shipping) return 'Your delivery price is ready. Check the full total below.';
  if(result?.products) return 'Choose a food below to get started.';
  if(result?.permissionExpiresAt) return 'You can continue shopping. Please check your cart again.';
  if(result?.message === 'New sandbox cart ready. Your previous receipt is preserved.') return 'Your new cart is ready. Your previous receipt is saved.';
  return result?.message || 'You’re ready for the next step below.';
}
async function run(task){if(busy)return;busy=true;status.textContent='Please wait…';root.querySelectorAll('button').forEach(b=>b.disabled=true);try{const result=await task();await refresh();status.textContent=responseMessage(result);}catch(error){try{await refresh();}catch{}status.textContent=errors[error.message]||'We couldn’t finish this step. Your cart is saved, and we haven’t tried again automatically. Please ask the demo team for help.';}finally{busy=false;render();}}
root.addEventListener('submit',event=>{event.preventDefault();const code=document.querySelector('#demo-code')?.value;if(code)run(()=>post('login',{code},'/api/login'));});
root.addEventListener('click',event=>{const target=event.target.closest('[data-action]');if(!target||busy||target.disabled)return;const action=target.dataset.action;
  if(action==='browse'){browsing=true;detail=null;render();return;}if(action==='showCart'){browsing=false;detail=null;render();return;}
  if(action==='search'){detail=null;return run(()=>post('search',{query:'cat food'}));}
  if(action==='details')return run(async()=>{detail=await post('details',{productId:target.dataset.product});return {};}).then(()=>root.querySelector('.product-detail')?.scrollIntoView?.({block:'start',behavior:'instant'}));
  if(action==='choose'||action==='decline'){if(action==='choose'&&!document.querySelector('#product-consent')?.checked){status.textContent='Tick the box to confirm your food and size before adding it to the cart.';return;}const optionIds=[...document.querySelectorAll('[data-option]')].map(x=>x.value);return run(async()=>{const r=await post('choose',{productId:detail.id,optionIds,substitute:true,ownerDecision:action==='decline'?'decline':'approve'});detail=null;browsing=action==='decline';return r;});}
  if(action==='shipping')return run(()=>post('shipping',{shippingOptionId:target.dataset.shipping}));
  if(action==='approveCart'){if(!document.querySelector('#delivery-consent')?.checked){status.textContent='Check the total and delivery information, then tick the box to continue.';return;}return run(()=>post('approveCart',{acceptUnknownDelivery:true}));}
  if(['renewPermission','renewEnrollment','startNew'].includes(action))return run(async()=>{const r=await post(action,{ownerDecision:'approve'});if(action==='startNew'){detail=null;browsing=false;await post('search',{query:'cat food'});}return r;});
  run(()=>post(action));
});
refresh().then(async()=>{if(new URLSearchParams(location.search).get('reap-return')==='1'&&view?.enrollment&&!view.receipt){await run(async()=>{if(view.checkout){const c=await post('status');return {message:c.checkoutId?'Your test order is complete. Your receipt is saved below.':`Welcome back. Your test order is ${readableStatus(c.status).toLowerCase()}. We’ll show a receipt once Reap confirms it.`};}const e=await post('enrollmentStatus');return {message:e.status==='ACTIVE'?'Your test card is ready. Check your cart before placing the test order.':`Welcome back. Card setup is ${readableStatus(e.status).toLowerCase()}. Returning here does not mean setup is complete.`};});}else if(view && !view.selection && !view.products.length){await run(()=>post('search',{query:'cat food'}));status.textContent='Choose a food below to get started.';}else status.textContent='Welcome back. Continue shopping below.';}).catch(error=>{status.textContent=errors[error.message]||'We couldn’t open the demo shop. Please reload the page. No order was placed.';});
